apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  selector:
    app: pihole
  ports:
  - port: 80
    name: pihole-web
    targetPort: 80
  - port: 53
    name: pihole-dns
    targetPort: 53
  type: NodePort