apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 53
        - containerPort: 80
        env:
          - name: TZ
            value: America/Chicago
          - name: DNS1
            value: 1.1.1.1
          - name: DNS2
            value: 1.0.0.1
          - name: WEBPASSWORD
            value: foobar